/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmosecuencial;

import javax.swing.JOptionPane;

/**
 *
 * @author aldair
 */
public class Ejercicio6 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio6
     */
    public Ejercicio6() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtPalabras.requestFocusInWindow();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCentimetros = new javax.swing.JTextField();
        txtColores = new javax.swing.JTextField();
        txtTpgar = new javax.swing.JTextField();
        txtPalabras = new javax.swing.JTextField();
        cmdBorrar = new javax.swing.JButton();
        cmdCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("# De Palabras");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setText("# De Centimetros");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel4.setText("# De Colores");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel5.setText("Total A Pagar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Procesador De Datos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        txtCentimetros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCentimetrosKeyTyped(evt);
            }
        });
        jPanel1.add(txtCentimetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 70, 40));

        txtColores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColoresKeyTyped(evt);
            }
        });
        jPanel1.add(txtColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 40, 40));

        txtTpgar.setEditable(false);
        jPanel1.add(txtTpgar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 250, 40));

        txtPalabras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabrasKeyTyped(evt);
            }
        });
        jPanel1.add(txtPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, 40));

        cmdBorrar.setBackground(new java.awt.Color(255, 102, 255));
        cmdBorrar.setForeground(new java.awt.Color(255, 255, 255));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 70, -1));

        cmdCalcular.setBackground(new java.awt.Color(204, 102, 255));
        cmdCalcular.setForeground(new java.awt.Color(255, 255, 255));
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aldair\\Desktop\\istock_000019699924small.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        
        double pal, col, cent, res1, res2, res3, tpagar; 
        
        if(txtPalabras.getText().trim().isEmpty() && txtCentimetros.getText().trim().isEmpty() && txtColores.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por favor LLENE los espacios en blanco");
        }else if(txtPalabras.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"por favor indique cuantas palabras tiene su articulo","ERROR",JOptionPane.WARNING_MESSAGE);
        }else if(txtCentimetros.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"por favor indique cuantos centimetros tiene su articulo","ERROR",JOptionPane.WARNING_MESSAGE);
        }else if(txtColores.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"por favor indique cuantos colores tiene su articulo","ERROR",JOptionPane.WARNING_MESSAGE);
        }else{   
        
         try{   
        pal=Double.parseDouble(txtPalabras.getText());
        cent=Double.parseDouble(txtCentimetros.getText());
        col=Double.parseDouble(txtColores.getText());
        
        res1=(pal*20000);
        res2=(cent*15000);
        res3=(col*25000);
        tpagar=(res1+res2+res3);
        
        
        txtTpgar.setText(""+tpagar);
         
         }
         catch(Exception w){
             JOptionPane.showMessageDialog(null,"hay cantidades incorrectas, por favor verificar","ERROR",JOptionPane.INFORMATION_MESSAGE);
         }
         }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        
        txtPalabras.setText("");
        txtCentimetros.setText("");
        txtColores.setText("");
        
        txtTpgar.setText("");
        
        txtPalabras.requestFocusInWindow();
              
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtPalabrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabrasKeyTyped
        
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar() != '.'){
            getToolkit();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtPalabrasKeyTyped

    private void txtCentimetrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCentimetrosKeyTyped
        
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar() != '.'){
            getToolkit();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtCentimetrosKeyTyped

    private void txtColoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColoresKeyTyped
        
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar() != '.'){
            getToolkit();
            
            evt.consume();
        }
    }//GEN-LAST:event_txtColoresKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCentimetros;
    private javax.swing.JTextField txtColores;
    private javax.swing.JTextField txtPalabras;
    private javax.swing.JTextField txtTpgar;
    // End of variables declaration//GEN-END:variables
}
